version: "3.7"
services:
  app:
    build:
      args:
        user: master
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: master-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - master
  db:
    image: mysql:8.0
    container_name: master-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - master
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST:db
      - MYSQL_USERNAME:${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD:${DB_PASSWORD}
    networks:
      - master

  nginx:
    image: nginx:alpine
    container_name: master-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - master

networks:
  master:
    driver: bridge
